// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyTroDaiLoi.Data;

#nullable disable

namespace QuanLyTroDaiLoi.Migrations
{
    [DbContext(typeof(TroDbContext))]
    [Migration("20250903092728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.CauHinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonGiaDien = 3500m,
                            DonGiaNuoc = 10000m
                        });
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.CauHinhThue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaThueNha")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaThuePhong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhThues");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.DonVi", b =>
                {
                    b.Property<int>("DonViId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonViId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDonVi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SoDienCu")
                        .HasColumnType("integer");

                    b.Property<int?>("SoDienMoi")
                        .HasColumnType("integer");

                    b.Property<int>("SoNuocCu")
                        .HasColumnType("integer");

                    b.Property<int?>("SoNuocMoi")
                        .HasColumnType("integer");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonViId");

                    b.ToTable("DonVis");

                    b.HasData(
                        new
                        {
                            DonViId = 1,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 1",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 2,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 2",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 3,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 3",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 4,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 4",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 5,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 5",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 6,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 6",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 7,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 7",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 8,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 8",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 9,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 9",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 10,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 10",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 11,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 11",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 12,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 12",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 13,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 13",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 14,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 14",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 15,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 15",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 16,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 16",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 17,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 17",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 18,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 18",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 19,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 19",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 20,
                            GhiChu = "",
                            GiaThue = 1500000m,
                            LoaiDonVi = "Phong",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Phòng 20",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 101,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 1",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 102,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 2",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 103,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 3",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 104,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 4",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 105,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 5",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 106,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 6",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 107,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 7",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 108,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 8",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 109,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 9",
                            TienDien = 0m,
                            TienNuoc = 0m
                        },
                        new
                        {
                            DonViId = 110,
                            GhiChu = "",
                            GiaThue = 5000000m,
                            LoaiDonVi = "Nha",
                            SoDienCu = 0,
                            SoNuocCu = 0,
                            TenDonVi = "Nhà 10",
                            TienDien = 0m,
                            TienNuoc = 0m
                        });
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.DonViThang", b =>
                {
                    b.Property<int>("DonViThangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonViThangId"));

                    b.Property<int>("DonViId")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<int>("SoDienCu")
                        .HasColumnType("integer");

                    b.Property<int>("SoDienMoi")
                        .HasColumnType("integer");

                    b.Property<int>("SoNuocCu")
                        .HasColumnType("integer");

                    b.Property<int>("SoNuocMoi")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonViThangId");

                    b.HasIndex("DonViId");

                    b.ToTable("DonViThangs");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HoaDonId"));

                    b.Property<int>("DienCu")
                        .HasColumnType("integer");

                    b.Property<int>("DienMoi")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGiaDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonViId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NuocCu")
                        .HasColumnType("integer");

                    b.Property<int>("NuocMoi")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoaDonId");

                    b.HasIndex("DonViId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.NguoiThue", b =>
                {
                    b.Property<int>("NguoiThueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NguoiThueId"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DonViId")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NguoiThueId");

                    b.HasIndex("DonViId");

                    b.ToTable("NguoiThues");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.PhiKhac", b =>
                {
                    b.Property<int>("PhiKhacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhiKhacId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonViId")
                        .HasColumnType("integer");

                    b.Property<int?>("DonViThangId")
                        .HasColumnType("integer");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PhiKhacId");

                    b.HasIndex("DonViId");

                    b.HasIndex("DonViThangId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("PhiKhacs");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.DonViThang", b =>
                {
                    b.HasOne("QuanLyTroDaiLoi.Models.DonVi", "DonVi")
                        .WithMany("DonViThangs")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyTroDaiLoi.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.NguoiThue", b =>
                {
                    b.HasOne("QuanLyTroDaiLoi.Models.DonVi", "DonVi")
                        .WithMany("NguoiThues")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.PhiKhac", b =>
                {
                    b.HasOne("QuanLyTroDaiLoi.Models.DonVi", "DonVi")
                        .WithMany("PhiKhacs")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTroDaiLoi.Models.DonViThang", null)
                        .WithMany("PhiKhacs")
                        .HasForeignKey("DonViThangId");

                    b.HasOne("QuanLyTroDaiLoi.Models.HoaDon", "HoaDon")
                        .WithMany("PhiKhacs")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.DonVi", b =>
                {
                    b.Navigation("DonViThangs");

                    b.Navigation("NguoiThues");

                    b.Navigation("PhiKhacs");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.DonViThang", b =>
                {
                    b.Navigation("PhiKhacs");
                });

            modelBuilder.Entity("QuanLyTroDaiLoi.Models.HoaDon", b =>
                {
                    b.Navigation("PhiKhacs");
                });
#pragma warning restore 612, 618
        }
    }
}
